M48
; DRILL file KiCad 10.0.5 date 2026-09-01T01:03:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-01T01:03:17-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X150.0Y-82.18
X156.0Y-82.18
T2
X122.5Y-79.5
X141.5Y-143.5
X166.5Y-143.5
X181.0Y-79.5
M30
